//H&B WORK
import hb1 from "../public/works/hip&bones/1.jpg";
import hb2 from "../public/works/hip&bones/2.jpg";
import hb3 from "../public/works/hip&bones/3.jpg";
import hb4 from "../public/works/hip&bones/4.jpg";
import hb5 from "../public/works/hip&bones/5.jpg";
import hb6 from "../public/works/hip&bones/6.jpg";
import hb7 from "../public/works/hip&bones/7.jpg";
import hb8 from "../public/works/hip&bones/8.jpg";
import hb9 from "../public/works/hip&bones/9.jpg";

//CANDLES
import candles1 from "../public/works/candles/1.jpg";

//ARTIST
const artists = [
  {
    name: "Rondo",
    lastName: "Banks",
    bio: `Luka Alexander Hollinger, also known as Rondo Banks, was born and raised in Montreal, Canada. At the age of 16, Rondo followed his mother to Havana as she pursued her career as an artist. He quickly fell in love with the people and the city, leading him to make it his home. He now lives part time between Montreal and Havana, finding new ways to express himself and share his messages through all the mediums of art he loves; Music, Dance, Photography, Cinema, Fashion and more. 
        He follows the light and does his best to make the world one.
        “United we are stronger”`,
    role: "Founder and CEO / Photographer",
    slug: "rondobanks",
    photo: "/luca.JPG",
    overlayImage: '/legra_overlayImage.png',
    signature: "/signature_luca.svg",
    works: [
      '/portfolios/rondobanks/rondobanks_1.jpg',
      '/portfolios/rondobanks/rondobanks_2.jpg',
      '/portfolios/rondobanks/rondobanks_3.jpg',
      '/portfolios/rondobanks/rondobanks_4.jpg',
      '/portfolios/rondobanks/rondobanks_5.jpg',
      '/portfolios/rondobanks/rondobanks_6.jpg',
      '/portfolios/rondobanks/rondobanks_7.jpg',
      '/portfolios/rondobanks/rondobanks_8.jpg',
      '/portfolios/rondobanks/rondobanks_9.jpg',
      '/portfolios/rondobanks/rondobanks_10.jpg',
      '/portfolios/rondobanks/rondobanks_11.jpg',
      '/portfolios/rondobanks/rondobanks_12.jpg',
      '/portfolios/rondobanks/rondobanks_13.jpg',
      '/portfolios/rondobanks/rondobanks_14.jpg',
      '/portfolios/rondobanks/rondobanks_15.jpg',
      '/portfolios/rondobanks/rondobanks_16.jpg',
      '/portfolios/rondobanks/rondobanks_17.jpg',
      '/portfolios/rondobanks/rondobanks_18.jpg',
      '/portfolios/rondobanks/rondobanks_19.jpg',
      '/portfolios/rondobanks/rondobanks_20.jpg',
      '/portfolios/rondobanks/rondobanks_21.jpg',
      '/portfolios/rondobanks/rondobanks_22.jpg',
      '/portfolios/rondobanks/rondobanks_23.jpg'
    ],
  },
  {
    name: "l.u.i.s.m.a.a.",
    bio: `Diseñador, artista visual, creador digital y fotógrafo cubano refleja su arte a partir de su fascinación por la manera en la que las tipografías y los elementos visuales pueden transmitir emociones y contar historias poderosas. Mediante la experimentación con el uso del estilo grunge de distintas épocas, técnicas analógicas, texturas y elementos imperfectos le permite crear piezas únicas buscando adentrarse aún más hacia lo alternativo. Su objetivo es seguir expresando su amor por lo que hace, en su búsqueda de nuevas técnicas y estilos con el fin de estar en constante evolución y compartiendo su visión a través de sus obras`,
    role: "Graphic Designer and Visual Artist",
    slug: "luismaa",
    photo: "/luismaa.jpg",
    overlayImage: '/luismaa_overlayImage.png',
    signature: "/signature_luismaa.svg",
    works: [
      '/portfolios/luismaa/luismaa_1.jpg',
      '/portfolios/luismaa/luismaa_2.jpg',
      '/portfolios/luismaa/luismaa_3.jpg',
      '/portfolios/luismaa/luismaa_4.jpg',
      '/portfolios/luismaa/luismaa_5.jpeg',
      '/portfolios/luismaa/luismaa_6.jpg',
      '/portfolios/luismaa/luismaa_7.jpg',
      '/portfolios/luismaa/luismaa_8.jpg',
      '/portfolios/luismaa/luismaa_9.jpg',
      '/portfolios/luismaa/luismaa_10.jpg',
      '/portfolios/luismaa/luismaa_11.jpg',
      '/portfolios/luismaa/luismaa_12.jpg',
      '/portfolios/luismaa/luismaa_13.jpg',
      '/portfolios/luismaa/luismaa_14.jpg',
      '/portfolios/luismaa/luismaa_15.jpg',
      '/portfolios/luismaa/luismaa_16.jpg',
      '/portfolios/luismaa/luismaa_17.jpg',
      '/portfolios/luismaa/luismaa_18.jpg',
      '/portfolios/luismaa/luismaa_19.jpg',
      '/portfolios/luismaa/luismaa_20.jpeg',
      '/portfolios/luismaa/luismaa_21.jpg',
      '/portfolios/luismaa/luismaa_22.jpg',
      '/portfolios/luismaa/luismaa_23.jpg',
      '/portfolios/luismaa/luismaa_24.jpg',
      '/portfolios/luismaa/luismaa_25.jpg',
      '/portfolios/luismaa/luismaa_26.jpg',
      '/portfolios/luismaa/luismaa_27.jpg',
      '/portfolios/luismaa/luismaa_28.jpg',
      '/portfolios/luismaa/luismaa_29.jpg',
      '/portfolios/luismaa/luismaa_30.jpg',
    ],
  },
  {
    name: "Legra",
    lastName: "Brooks",
    bio: `Cuban creator and visual artist obsessed with shapes and colors, describes his surroundings through subjective and abstract photography with a distinct photographic style that simulates movement and translation. His work has a significant focus on how he perceives light and objects through his vision. A graduate of the Creative Photography School of Havana (EFCH) in 2017, he delves into the emerging Havana cultural scene, capturing portraits of renowned personalities in the country such as Andrés Levin, Roberto Fabelo, Thaimi Albariño, Jorge Perugorria, etc.`,
    role: "fotografo",
    slug: "legrabrooks",
    photo: "/legra.jpg",
    overlayImage: '/legra_overlayImage.png',
    signature: "/signature_legra.svg",
    works: [
      '/portfolios/legrabrooks/000092260013.JPEG',
      '/portfolios/legrabrooks/000092260035.JPEG',
      '/portfolios/legrabrooks/000092270006.JPEG',
      '/portfolios/legrabrooks/1334B36B-1640-43D0-BCF9-1BAE8CF0118F.JPEG',
      '/portfolios/legrabrooks/2021-04-14 09.27.15 1.jpg',
      '/portfolios/legrabrooks/IMG_2409.JPG',
      '/portfolios/legrabrooks/IMG_3220.jpg',
      '/portfolios/legrabrooks/IMG_3864.jpg',
      '/portfolios/legrabrooks/IMG_5526.jpg',
      '/portfolios/legrabrooks/IMG_7705 2.JPG',
      '/portfolios/legrabrooks/IMG_7710.JPG',
      '/portfolios/legrabrooks/IMG_7710.JPG',
      '/portfolios/legrabrooks/IMG_8128.jpg',
      '/portfolios/legrabrooks/IMG_8146.jpg',
      '/portfolios/legrabrooks/legrabrook_1.jpg',
      '/portfolios/legrabrooks/legrabrook_2.jpg',
      '/portfolios/legrabrooks/legrabrook_3.jpg',
      '/portfolios/legrabrooks/legrabrook_4.jpg',
      '/portfolios/legrabrooks/legrabrook_5.jpg',
      '/portfolios/legrabrooks/legrabrook_6.jpg',
      '/portfolios/legrabrooks/legrabrook_7.jpg',
      '/portfolios/legrabrooks/legrabrook_8.jpg',
      '/portfolios/legrabrooks/legrabrook_9.jpg',
      '/portfolios/legrabrooks/legrabrook_10.jpg',
      '/portfolios/legrabrooks/legrabrook_11.jpg'
    ],
  },
  {
    name: "Osmel Azcuy",
    bio: `Osmel Portuondo Azcuy, born in Havana, Cuba, in 1985, is a multifaceted artist. He seeks to portray the everyday events of his city and its inhabitants, creating a mosaic of deeply personal and collective experiences in the process. Osmel's profound interest in photography was inherited from his grandfather, a professional photographer, and solidified in shared moments in the darkroom of his home.

    The camera became his tool for crafting social chronicles that navigate the realm between private and collective stories.`,
    role: "fotografo",
    slug: "osmelazcuy",
    photo: "/osmel.jpg",
    signature: "/signature_osmel.svg",
    works: [
      '/portfolios/osmelazcuy/osmelazcuy_1.jpg',
      '/portfolios/osmelazcuy/osmelazcuy_2.jpg',
      '/portfolios/osmelazcuy/osmelazcuy_3.jpg',
      '/portfolios/osmelazcuy/osmelazcuy_4.jpg',
      '/portfolios/osmelazcuy/osmelazcuy_5.jpg',
      '/portfolios/osmelazcuy/osmelazcuy_6.jpg',
      '/portfolios/osmelazcuy/osmelazcuy_7.jpg',
      '/portfolios/osmelazcuy/osmelazcuy_8.jpg',
      '/portfolios/osmelazcuy/osmelazcuy_9.jpg',
      '/portfolios/osmelazcuy/osmelazcuy_10.jpg',
      '/portfolios/osmelazcuy/osmelazcuy_11.jpg',
      '/portfolios/osmelazcuy/osmelazcuy_12.jpg',
      '/portfolios/osmelazcuy/osmelazcuy_13.jpg',
      '/portfolios/osmelazcuy/osmelazcuy_14.jpg',
      '/portfolios/osmelazcuy/osmelazcuy_15.jpg',
      '/portfolios/osmelazcuy/osmelazcuy_16.jpg',
      '/portfolios/osmelazcuy/osmelazcuy_17.jpg',
      '/portfolios/osmelazcuy/osmelazcuy_18.jpg',
      '/portfolios/osmelazcuy/osmelazcuy_19.jpg',
      '/portfolios/osmelazcuy/osmelazcuy_20.jpg',
      '/portfolios/osmelazcuy/osmelazcuy_21.jpg',
      '/portfolios/osmelazcuy/osmelazcuy_22.jpg',
      '/portfolios/osmelazcuy/osmelazcuy_23.jpg',
      '/portfolios/osmelazcuy/osmelazcuy_24.jpg',
    ],
  },
  {
    name: "LUW",
    bio: `Luis Ronaldo Benitez Reyes aka Luw is a digital artist from Cienfuegos, Cuba. With his bold vision and dedication, Luis wants to break stereotypes and challenge established artistic conventions, in Cuba and around the world. His work is often vibrant, colorful and full of life, capturing the essence and beauty of the human being in new and unexpected ways.`,
    role: "designer",
    slug: "luw",
    photo: "/osmel.jpg",
    signature: "/signature_osmel.svg",
    works: [],
  },
];

export { hb1, hb2, hb3, hb4, hb5, hb6, hb7, hb8, hb9, candles1, artists };
